### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by bryantAXS** [viromedia/ViroARSampleApp#3]
After install both Viro and the ViroARSampleApp today I'm getting this error (plug a handfull of others) on the initial load.

```
index.bundle?platform=ios&dev=true:7683 `ViroARSceneNavigator` has no propType for native prop `VRTARSceneNavigator.autofocus` of native type `BOOL`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
```

```
react-native-cli: 2.0.1
react-native: 0.49.3
```

**Comment by VikAdvani** [comment]
Hi @bryantAXS, I've updated  ViroARSampleApp to use the latest version of viro react which is 2.4. Can you do a fresh checkout of ViroARSample and do a fresh install of the node modules: "rm -rf node_modules && npm install".

That should hopefully fix the issue you are seeing. If there are still issues, let us know. Thanks!

**Comment by jaswantjatav** [comment]
JASWANTs-MacBook-Pro:ViroARSampleApp jaswantsinghjatav$ ./setup-ide.sh --ios
Unknown option: 1
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output
==== Running iOS Setup Script ===
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:89: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Analyzing dependencies
[!] Unable to find a target named `true`, did find `ViroSampleAR`, `ViroSampleARTests`, `ViroSampleAR-tvOS`, and `ViroSampleAR-tvOSTests`.
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:100:in `open': [Xcodeproj] Unable to open `/Users/jaswantsinghjatav/ViroARSampleApp/ios/true.xcodeproj` because it doesn't exist. (RuntimeError)
	from proj_add_shell_script.rb:4:in `<main>'
File Doesn't Exist, Will Create: true/Info.plist
File Doesn't Exist, Will Create: true/Info.plist
File Doesn't Exist, Will Create: true/Info.plist
Set: Entry, ":NSCameraUsageDescription", Does Not Exist
cp: true/AppDelegate.m: No such file or directory
grep: true/AppDelegate.m: No such file or directory
sed: true/AppDelegate.m: No such file or directory

Please help me to sort this out.

Thanks in advance.

**Comment by jaswantjatav** [comment]
Please help me to sort this out.

Thanks in Advance.

**Comment by VikAdvani** [comment]
Hi @jaswantjatav, something very strange is happening here. The script should **not** be looking for true.xcodeproj. What shell are you using? Perhaps the shell is executing script incorrectly. Can you try using the normal bash shell that ships with mac?

**Comment by kristinwilk** [comment]
I am running into the same exact issue. What happens is when I run './setup-ide.sh ios', it changes my Podfile target to 'true', instead of my project name. Even when I change it back to my target name, it keeps changing the file, and this error keeps displaying.

**Comment by kristinwilk** [comment]
Nevermind, solved the issue...at least for me, I did not have a project name set up in package.json.
