### ISSUE TITLE
Android crash on start

### ISSUE THREAD

**Issue by nbastoWM** [viromedia/ViroARSampleApp#9]
Hi,
I'm trying to use this project in Android. I've tried with several supported devices (Nexus 6P, OP3T, OP6, S8, S9, J7) and the sample app crashes all the time. I've tried through "Testbed" and as a standalone App and the result is the same.

The logcat for this error:

```
12-06 10:28:58.222 24420 24420 E AndroidRuntime: FATAL EXCEPTION: main
12-06 10:28:58.222 24420 24420 E AndroidRuntime: Process: com.viromedia.viromedia, PID: 24420
12-06 10:28:58.222 24420 24420 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at java.lang.StringBuilder.<init>(StringBuilder.java:113)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerImpl$JSExceptionLogger.log(DevSupportManagerImpl.java:301)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerImpl.handleException(DevSupportManagerImpl.java:285)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:309)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:693)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
12-06 10:28:58.222 24420 24420 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-06 10:29:00.664   828  2798 W ActivityManager:   Force finishing activity com.viromedia.viromedia/.ViroTestBedViroActivity
12-06 10:29:00.682   828   845 I ActivityManager: Showing crash dialog for package com.viromedia.viromedia u0

```

**Comment by VikAdvani** [comment]
Hi @nbastoWM, I just checked out the project, did an npm install, ran setup-ide.sh and ran the app in Testbed and standalone on a Samsung s9. I'm unable to reproduce what you are seeing. Is the crash 100% reproducible for you? 

Did you change anything in the project(such as the package.json, etc)?
